import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(channel="chrome", headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://blueyonderalphaapac.b2clogin.com/blueyonderalphaapac.onmicrosoft.com/b2c_1a_signin_group_9/oauth2/v2.0/authorize?client_id=308d3b34-ba5e-4f41-ba17-f56157e86b4a&redirect_uri=https%3a%2f%2fblueyonderapac.b2clogin.com%2fblueyonderapac.onmicrosoft.com%2foauth2%2fauthresp&response_type=code&scope=openid+profile+email&response_mode=form_post&nonce=1nPpfM5yCRHm4L%2fpcXKxwQ%3d%3d&domain_hint=nike-test-au&realmId=a141a45b-c490-49c3-9bd7-9f6b000229e9&realmTenantName=blueyonderalphaapac&idpCommaDelimiterConverted=a141a45b-c490-49c3-9bd7-9f6b000229e9_3f872991-2c5b-4c57-aee5-765348237e1f%2ca141a45b-c490-49c3-9bd7-9f6b000229e9_c7b58e7e-116c-49e5-beb0-1cfa563c11b3%2cidp&prompt=login&state=StateProperties%3deyJTSUQiOiJ4LW1zLWNwaW0tcmM6Y2VjYTZiZTYtNGM2MC00ODY1LWJjMzQtYzQ2YmQ2ZjU3NmU5IiwiVElEIjoiMDY5MmQwMGItOWM2YS00MjRiLTgwZDktNTYyYmNlOGNmMDZiIiwiVE9JRCI6IjI2NTkzOTVlLTY0MmMtNDA2My1hNjgxLWVlYzBhOGMwMWQ4ZCJ9")
    page.get_by_role("link", name="NIKE APLA (SSO)").click()
    page.goto("https://nika-aztms-sso-ts1.jdadelivers.com/tm/framework/Frame.jsp")
    page.locator("frame[name=\"i2ui_shell_content\"]").content_frame.locator("#TREECELL_solutions_1_row a[href*=\"tmria/lbp.jsp\"]").click()
    page.get_by_role("link", name="NIKE APLA (SSO)").click()
    page.goto("https://nika-aztms-sb-ts1.jdadelivers.com/tmria/lbp.jsp?locale=en_US&returnURL=https://nika-aztms-sso-ts1.jdadelivers.com:443/tm&TimeStampID=1789091601757")
    page.get_by_role("tab", name="Shipment (1)").get_by_label("Close").click()
    page.get_by_role("tab", name="Shipment Legs of Shipment").get_by_label("Close").click()
    page.get_by_role("button", name="Close", exact=True).click()
    page.get_by_text("Shipment", exact=True).dblclick()
    page.locator("div").filter(has_text=re.compile(r"^ShipmentLoadsOptimization RequestsUnrouteable Shipments$")).first.click()
    page.locator('textarea[name^="shipmentNumber"]').click()
    page.locator('textarea[name^="shipmentNumber"]').fill("TEST091000031")
    page.locator('textarea[name^="shipmentNumber"]').press("Enter")
    page.locator("#isc_RN span[eventpart='valueicon']").click()
    page.get_by_role("button", name="Cascade").click()
    page.get_by_text("Shipment Legs").click()
    page.locator("#isc_112 span[eventpart='valueicon']").click()
    page.get_by_role("button", name="Planning Operations").click()
    page.get_by_text("Select for Optimization", exact=True).click()
    page.get_by_role("button", name="Planning Operations").click()
    page.get_by_text("Optimize").click()
    page.locator("#isc_1CL").click()
    page.get_by_text("PO", exact=True).click()
    page.get_by_label("Create Optimization Request").get_by_role("button", name="Submit").click()
    page.get_by_role("button", name="Load Operations").click()
    page.get_by_text("Assign to New Load", exact=True).click()
    page.locator("td.otherToolStripButton").filter(has_text=re.compile(r"^Cascade$")).last.click()
    page.locator("td.menuTitleField nobr").filter(has_text=re.compile(r"^Loads$")).click()
    page.locator(".checkboxFalse").first.click()
    page.get_by_role("button", name="Release Shipment Plan").click()
    page.locator("td.otherToolStripButton").filter(has_text=re.compile(r"^Tender Operations$")).last.click()
    page.locator("td.menuTitleField").filter(has_text=re.compile(r"^Load Tender$")).click()
    page.locator("#isc_P2").click()
    page.get_by_text("Auto-Accept Tender", exact=True).click()
    page.get_by_text("Auto-Accept Tender", exact=True).click()
    page.get_by_role("textbox", name="Accepted By").click()
    page.get_by_role("textbox", name="Accepted By").fill("VGTest")
    page.get_by_label("Tender for Selected Loads").get_by_role("button", name="Submit").click()
    page.locator("td.otherToolStripButton").filter(has_text=re.compile(r"^Tender Operations$")).last.click()
    page.locator("td.menuTitleField").filter(has_text=re.compile(r"^Accept Load Tender$")).click()
    page.get_by_role("textbox", name="Accepted By").click()
    page.get_by_role("textbox", name="Accepted By").fill("VGTest")
    page.get_by_label("Tender Accept Selected Loads").get_by_role("button", name="Submit").click()
    page.get_by_role("tab", name="Load of Shipment Leg").get_by_label("Close").click()
    page.get_by_role("tab", name="Shipment Legs of Shipment").get_by_label("Close").click()
    page.get_by_role("button", name="Close", exact=True).click()
    page.get_by_role("button", name="Logout").click()
    page.goto("https://tmslogout.jdadelivers.com/logout.htm")
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
